version: '3.7'

services:
  garrysmod:
    build: .
    container_name: garrysmod
    ports:
      - 27031:27015/tcp
      - 27031:27015/udp
    env_file:
      - ./.env
    volumes:
      - ./server.cfg:/opt/steam/garrysmod/cfg/server.cfg
