version: '3.7'

services:
  ut99:
    build: .
    container_name: ut99
    ports:
      - 7790-7794:7777-7781/tcp
      - 7790-7794:7777-7781/udp
      - 27900:27900/tcp
      - 27900:27900/udp
      - 9999:80
    env_file:
      - ./.env
    privileged: true
    stdin_open: true
    tty: true
